[package]
name = "moonbit-showcase-fft"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
divan = "0.1.14"
pretty_assertions = "1.4.1"
rustfft = "6.2.0"

[[bench]]
name = "fft"
harness = false
path = "src/main.rs"
